/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.FlowLayout;
import javax.swing.JPanel;
import java.awt.image.BufferedImage;
/**
 *
 * @author Renan
 */
public class PanelImageOriginal extends javax.swing.JInternalFrame {

    /**
     * Creates new form PanelBoard
     */
    private BufferedImage image;
    private JPanel panel = new JPanel();

    public PanelImageOriginal() {
        initComponents();
        panel.setLayout(new FlowLayout());
        panel = new JPanel() {
            @Override
            public void paint(Graphics g) { // paint() method
                super.paint(g);
                g.setColor(Color.black);
                g.drawImage(image, 0, 0, null);
            }
        };
        getContentPane().add(panel);
        pack();
        setVisible(true);
        //pack();
        //setVisible(true);
        repaint(); 
    }

    public void setPanel(JPanel panel) {
        this.panel = panel;
    }
    public JPanel getPanel() {
        return this.panel;
    }

    public void setImage(BufferedImage image) {
        this.image = image;
    }

    public BufferedImage getImage() {
        return this.image;
    }

    public int getWidth() {
        return super.getWidth();
    }

    public int getHeight() {
        return super.getHeight();
    }

    public int getCenterX() {
        return super.getWidth()/2;
    }

    public int getCenterY() {
        return super.getHeight()/2;
    }
    
   public void paint(Graphics g) {
       super.paint(g);
       //g.drawImage(image, 75, 75, null);
   }

   public Dimension getPreferredSize() {
      return new Dimension(355, 445);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setTitle("Board");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
