/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.awt.event.ItemEvent;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.image.BufferedImage;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JInternalFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.imageio.ImageIO;
import java.net.URL;


import panels.PanelImageOperations;
import panels.PanelImage;

import imageprocessing.filters.Filter;
import imageprocessing.operators.Operator;

/**
 *
 * @author Renan
 */
public class PanelImageOperations extends javax.swing.JInternalFrame {
    private BufferedImage image, image2;
    private BufferedImage imageResult;
    private int[][] imageMatrix;
    private int[][] imageMatrix1;
    private int[][] imageMatrix2; 
    private int imgWidth;
    private int imgHeight;
    private int imgValorMaximo;

    /*
    public void setPanelImageInput(PanelImage panel) {
        this.panelImageInput = panel;
    }
    */
    /**
     * Creates new form PanelImageOperations
     */
    public PanelImageOperations() {
        initComponents();
        
        operacoesComboBox.removeAllItems();
        operacoesComboBox.addItem("Soma");
        operacoesComboBox.addItem("Divisao");
        operacoesComboBox.addItem("Multiplicacao");
        operacoesComboBox.addItem("Subtracao");
        operacoesComboBox.addItem("OR");
        operacoesComboBox.addItem("AND");
        operacoesComboBox.addItem("XOR");
        panelImageOriginal.setBackground(Color.GRAY);
        panelImageOriginal2.setBackground(Color.GRAY);
        panelImageResult.setBackground(Color.GRAY);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.drawImage(image, 230, 50, null);
        g.drawImage(image2, 550, 50, null);
        //g.drawImage(imageResult, 380, 420, null);

        //panelImageResult.getGraphics().drawImage(imageResult, 320, 50, null);
    }

    /*
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        panelImageOriginal.getGraphics().drawImage(image, 0, 0, null);
        panelImageOriginal.repaint();

    }
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        operacoesComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        aplicarNaImagemButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelImageOriginal = new javax.swing.JPanel();
        selecionarImgButton = new javax.swing.JButton();
        panelImageOriginal2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selecionarImgButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panelImageResult = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Operações entre Imagens");
        setPreferredSize(new java.awt.Dimension(890, 700));

        operacoesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        operacoesComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                operacoesComboBoxItemStateChanged(evt);
            }
        });
        operacoesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operacoesComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Operações entre Imagens");

        aplicarNaImagemButton.setText("Aplicar na Imagem");
        aplicarNaImagemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarNaImagemButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecionar Imagem1");

        panelImageOriginal.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout panelImageOriginalLayout = new javax.swing.GroupLayout(panelImageOriginal);
        panelImageOriginal.setLayout(panelImageOriginalLayout);
        panelImageOriginalLayout.setHorizontalGroup(
            panelImageOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panelImageOriginalLayout.setVerticalGroup(
            panelImageOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        selecionarImgButton.setText("Selecionar");
        selecionarImgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarImgButtonActionPerformed(evt);
            }
        });

        panelImageOriginal2.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout panelImageOriginal2Layout = new javax.swing.GroupLayout(panelImageOriginal2);
        panelImageOriginal2.setLayout(panelImageOriginal2Layout);
        panelImageOriginal2Layout.setHorizontalGroup(
            panelImageOriginal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panelImageOriginal2Layout.setVerticalGroup(
            panelImageOriginal2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel3.setText("Imagem 1");

        jLabel4.setText("Imagem 2");

        selecionarImgButton2.setText("Selecionar");
        selecionarImgButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarImgButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Selecionar Imagem2");

        panelImageResult.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout panelImageResultLayout = new javax.swing.GroupLayout(panelImageResult);
        panelImageResult.setLayout(panelImageResultLayout);
        panelImageResultLayout.setHorizontalGroup(
            panelImageResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panelImageResultLayout.setVerticalGroup(
            panelImageResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel6.setText("Imagem Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelImageResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(selecionarImgButton)
                                .addComponent(aplicarNaImagemButton)
                                .addComponent(jLabel5)
                                .addComponent(selecionarImgButton2))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(operacoesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(panelImageOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelImageOriginal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImageOriginal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImageOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(operacoesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aplicarNaImagemButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionarImgButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionarImgButton2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panelImageResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aplicarNaImagemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarNaImagemButtonActionPerformed
        // TODO add your handling code here:
        if(operacoesComboBox.getSelectedItem().equals("Soma")) {
            this.imageResult = Operator.addition(imageMatrix, imageMatrix2, true);
            this.getGraphics().drawImage(imageResult, 380, 420, null);
            
        } else if(operacoesComboBox.getSelectedItem().equals("Divisao")) {
            this.imageResult = Operator.division(imageMatrix, imageMatrix2, true);
            this.getGraphics().drawImage(imageResult, 380, 420, null);
            
        } else if(operacoesComboBox.getSelectedItem().equals("Multiplicacao")) {
            this.imageResult = Operator.multiplication(imageMatrix, imageMatrix2, true);
            this.getGraphics().drawImage(imageResult, 380, 420, null);

        } else if(operacoesComboBox.getSelectedItem().equals("Subtracao")) {
            this.imageResult = Operator.subtraction(imageMatrix, imageMatrix2, true);
            this.getGraphics().drawImage(imageResult, 380, 420, null);

        } else if(operacoesComboBox.getSelectedItem().equals("OR")) {
            this.imageResult = Operator.OR(imageMatrix, imageMatrix2, true);
            this.getGraphics().drawImage(imageResult, 380, 420, null);

        } else if(operacoesComboBox.getSelectedItem().equals("AND")) {
            this.imageResult = Operator.AND(imageMatrix, imageMatrix2, true);
            this.getGraphics().drawImage(imageResult, 380, 420, null);

        } else if(operacoesComboBox.getSelectedItem().equals("XOR")) {
            this.imageResult = Operator.XOR(imageMatrix, imageMatrix2, true);
            this.getGraphics().drawImage(imageResult, 380, 420, null);

        }
    }//GEN-LAST:event_aplicarNaImagemButtonActionPerformed

    private void selecionarImgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarImgButtonActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File("src/images/"));
            FileNameExtensionFilter filter = new FileNameExtensionFilter("PGM Images", "pgm");
            fileChooser.setFileFilter(filter);
            int returnVal = fileChooser.showOpenDialog(aplicarNaImagemButton);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                //imageMatrix1 = createImage(fileChooser.getSelectedFile());
                //populaImgInPanel(imageMatrix1, panelImageOriginal);
               // createImage(fileChooser.getSelectedFile());
               
                File path = fileChooser.getSelectedFile();
                System.out.println(path);
                createImage(path.getAbsolutePath());
                //btAplicaFiltro.setEnabled(true);
                //panelImgOutput.repaint();
                //panelImageOriginal.setImage(imgT);

                //panelImageInput.setImage(image);
                //panelImageInput.repaint();

                //panelImageOriginal.getGraphics().drawImage(image, 0, 0, null);
                //panelImageOriginal.repaint();
                this.repaint();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "OPS! N�o foi possivel carregar a imagem.");
        }
    }//GEN-LAST:event_selecionarImgButtonActionPerformed

    private void operacoesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operacoesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_operacoesComboBoxActionPerformed

    private void operacoesComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_operacoesComboBoxItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED && operacoesComboBox.getSelectedItem().equals("Soma")) {

        } else if(evt.getStateChange() == ItemEvent.SELECTED && operacoesComboBox.getSelectedItem().equals("Divisao")) {

        } else if(evt.getStateChange() == ItemEvent.SELECTED && operacoesComboBox.getSelectedItem().equals("Multiplicacao")) {

        } else if(evt.getStateChange() == ItemEvent.SELECTED && operacoesComboBox.getSelectedItem().equals("Subtracao")) {

        } else if(evt.getStateChange() == ItemEvent.SELECTED && operacoesComboBox.getSelectedItem().equals("OR")) {

        } else if(evt.getStateChange() == ItemEvent.SELECTED && operacoesComboBox.getSelectedItem().equals("AND")) {

        } else if(evt.getStateChange() == ItemEvent.SELECTED && operacoesComboBox.getSelectedItem().equals("XOR")) {

        }
    }//GEN-LAST:event_operacoesComboBoxItemStateChanged

    private void selecionarImgButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarImgButton2ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File("src/images/"));
            FileNameExtensionFilter filter = new FileNameExtensionFilter("PGM Images", "pgm");
            fileChooser.setFileFilter(filter);
            int returnVal = fileChooser.showOpenDialog(aplicarNaImagemButton);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File path = fileChooser.getSelectedFile();
                System.out.println(path);
                createImage2(path.getAbsolutePath());
                this.repaint();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "OPS! N�o foi possivel carregar a imagem.");
        }
    }//GEN-LAST:event_selecionarImgButton2ActionPerformed

    /**
     *  Ler o arquivo pgm e monta a popula a matriz imagem
     */
    public int[][] createImage(String path) {
        /*
        FileInputStream fileInputStream = null;
        Scanner scan = null;
        try {
            fileInputStream = new FileInputStream(file);
            scan = new Scanner(fileInputStream);
        } catch (FileNotFoundException ex) {
            //Logger.getLogger(PanelOperacoes.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Descarta a primeira linha
        scan.nextLine();
        // Read pic width, height and max value
        imgWidth = scan.nextInt();
        imgHeight = scan.nextInt();
        imgValorMaximo = scan.nextInt();
        */ 
        //BufferedImage bimg = null;
        int width;
        int height;

        InputStream inputStream = null;
        Scanner scan = null;
        try {

            System.out.println(path);
            inputStream = new FileInputStream(path);
            scan = new Scanner(inputStream);

            // Descarta a primeira linha
            scan.nextLine();
            // Read pic width, height and max value
            width = scan.nextInt();
            height = scan.nextInt();
            imgValorMaximo = scan.nextInt();

            BufferedImage bimg = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
            System.out.printf ("W : %d\n", width);
            System.out.printf ("H : %d\n", height);

            //width = i.getWidth();
            //height = i.getHeight();
            /*
            if (path == null)
                System.out.println("File Null");
            if (inputStream == null) 
                System.out.println("input Null");
            if (bimg == null)
                System.out.println("bimg Null");

            width = bimg.getWidth();
            height = bimg.getHeight();
            */
            //this.image = bimg;

            /**
            * Monta a matriz imagem com os pixels da imagem selecionada
            */
            imageMatrix = new int[width][height];

            for (int row = 0; row < height; row++) {
                for (int col = 0; col < width; col++) {
                    // Popula a matriz com os pixels da imagem
                    imageMatrix[row][col] = scan.nextInt();
                }
            }
            inputStream.close();

            /**
            * Monta a matriz imagem com os pixels da imagem selecionada
            */
            for (int row = 0; row < height; row++) {
                for (int col = 0; col < width; col++) {
                    // Prepara a imagem para ser desenhada no jpanel
                    bimg.setRGB(col, row, getCorPixel(imageMatrix[row][col]));
                }
            }

            this.image = bimg;


        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "OPS! criar a imagem.");
        }


        /*
        try {
            fileInputStream.close();
        } catch (IOException ex) {
            //Logger.getLogger(PanelOperacoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        return imageMatrix;
    }
    
    public int[][] createImage2(String path) {
        int width;
        int height;

        InputStream inputStream = null;
        Scanner scan = null;
        try {
            System.out.println(path);
            inputStream = new FileInputStream(path);
            scan = new Scanner(inputStream);

            // Descarta a primeira linha
            scan.nextLine();
            // Read pic width, height and max value
            width = scan.nextInt();
            height = scan.nextInt();
            imgValorMaximo = scan.nextInt();

            BufferedImage bimg = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);
            System.out.printf ("W : %d\n", width);
            System.out.printf ("H : %d\n", height);

            imageMatrix2 = new int[width][height];

            for (int row = 0; row < height; row++) {
                for (int col = 0; col < width; col++) {
                    // Popula a matriz com os pixels da imagem
                    imageMatrix2[row][col] = scan.nextInt();
                }
            }
            inputStream.close();

            /**
            * Monta a matriz imagem com os pixels da imagem selecionada
            */
            for (int row = 0; row < height; row++) {
                for (int col = 0; col < width; col++) {
                    // Prepara a imagem para ser desenhada no jpanel
                    bimg.setRGB(col, row, getCorPixel(imageMatrix2[row][col]));
                }
            }

            this.image2 = bimg;


        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "OPS! criar a imagem.");
        }
        return imageMatrix2;
    }

    /**
     * Exibe a imagem no jPanel
     *
     */

    /**
     * Retorna o valor em RGB de acordo com o valor do pixel
     */
    private int getCorPixel(int corRGB) {
        return new Color(corRGB, corRGB, corRGB).getRGB();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicarNaImagemButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> operacoesComboBox;
    private javax.swing.JPanel panelImageOriginal;
    private javax.swing.JPanel panelImageOriginal2;
    private javax.swing.JPanel panelImageResult;
    private javax.swing.JButton selecionarImgButton;
    private javax.swing.JButton selecionarImgButton2;
    // End of variables declaration//GEN-END:variables
}
