/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import imageprocessing.Normalization;
import java.awt.event.ItemEvent;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.image.BufferedImage;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JInternalFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.imageio.ImageIO;
import java.net.URL;
import java.lang.*;

import panels.PanelImageMorphology;
import panels.PanelImage;

import imageprocessing.filters.Filter;
import imageprocessing.transformations.morphology.Morphology;

/**
 *
 * @author Renan
 */
public class PanelImageMorphology extends javax.swing.JInternalFrame {
    //private PanelImage panelImageInput;
    private BufferedImage image;
    private BufferedImage imageResult;
    private BufferedImage imageOperator;
    private int[][] imageMatrix;
    private int[][] imageMatrix1;
    private int[][] imageMatrix2; 
    private int imgWidth;
    private int imgHeight;
    private int imgValorMaximo;
    private float valor;
    
    private boolean[][] kernel = { { false, true, false }, { true, true, true }, { false, true, false } };
    
    boolean ker[][] = new boolean[1][1];

    /*
    */
    /**
     * Creates new form PanelImageFilters
     */
    public PanelImageMorphology() {
        initComponents();
        
        
        filtrosComboBox.removeAllItems();
        filtrosComboBox.addItem("Erosion");
        filtrosComboBox.addItem("Dilation");
        filtrosComboBox.addItem("Opening");
        filtrosComboBox.addItem("Closure");
        filtrosComboBox.addItem("Dilate");
        filtrosComboBox.addItem("Erode");
        panelImageOriginal.setBackground(Color.GRAY);
        panelImageResult.setBackground(Color.GRAY);
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        g.drawImage(image, 230, 50, null);
    }

    /*
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtrosComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        aplicarNaImagemButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panelImageOriginal = new javax.swing.JPanel();
        selecionarImgButton = new javax.swing.JButton();
        panelImageResult = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        valorLabel = new javax.swing.JLabel();
        valorText = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Morfologias");
        setPreferredSize(new java.awt.Dimension(890, 444));

        filtrosComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filtrosComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtrosComboBoxItemStateChanged(evt);
            }
        });
        filtrosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrosComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Morfologias");

        aplicarNaImagemButton.setText("Aplicar na Imagem");
        aplicarNaImagemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicarNaImagemButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecionar Imagem");

        panelImageOriginal.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout panelImageOriginalLayout = new javax.swing.GroupLayout(panelImageOriginal);
        panelImageOriginal.setLayout(panelImageOriginalLayout);
        panelImageOriginalLayout.setHorizontalGroup(
            panelImageOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panelImageOriginalLayout.setVerticalGroup(
            panelImageOriginalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        selecionarImgButton.setText("Selecionar");
        selecionarImgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarImgButtonActionPerformed(evt);
            }
        });

        panelImageResult.setPreferredSize(new java.awt.Dimension(300, 300));

        javax.swing.GroupLayout panelImageResultLayout = new javax.swing.GroupLayout(panelImageResult);
        panelImageResult.setLayout(panelImageResultLayout);
        panelImageResultLayout.setHorizontalGroup(
            panelImageResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panelImageResultLayout.setVerticalGroup(
            panelImageResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel3.setText("Imagem Original");

        jLabel4.setText("Imagem Resultado");

        valorLabel.setText("Valor:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(selecionarImgButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(valorLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(filtrosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(aplicarNaImagemButton)))
                .addGap(43, 43, 43)
                .addComponent(panelImageOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelImageResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(216, 216, 216)
                .addComponent(jLabel4)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImageResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelImageOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filtrosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valorLabel)
                            .addComponent(valorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(aplicarNaImagemButton)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selecionarImgButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtrosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrosComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtrosComboBoxActionPerformed

    private void filtrosComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtrosComboBoxItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED && filtrosComboBox.getSelectedItem().equals("Erosion")) {
            valorLabel.setVisible(false);
            valorText.setVisible(false);
        } else if(evt.getStateChange() == ItemEvent.SELECTED && filtrosComboBox.getSelectedItem().equals("Dilation")) {
            valorLabel.setVisible(false);
            valorText.setVisible(false);
        } else if(evt.getStateChange() == ItemEvent.SELECTED && filtrosComboBox.getSelectedItem().equals("Opening")) {
            valorLabel.setVisible(true);
            valorText.setVisible(true);
        } else if(evt.getStateChange() == ItemEvent.SELECTED && filtrosComboBox.getSelectedItem().equals("Closure")) {
            valorLabel.setVisible(true);
            valorText.setVisible(true);
        } else if(evt.getStateChange() == ItemEvent.SELECTED && filtrosComboBox.getSelectedItem().equals("Dilate")) {
            valorLabel.setVisible(true);
            valorText.setVisible(true);
        } else if(evt.getStateChange() == ItemEvent.SELECTED && filtrosComboBox.getSelectedItem().equals("Erode")) {
            valorLabel.setVisible(true);
            valorText.setVisible(true);
        }
    }//GEN-LAST:event_filtrosComboBoxItemStateChanged

    private void aplicarNaImagemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarNaImagemButtonActionPerformed
        // TODO add your handling code here:
        if(filtrosComboBox.getSelectedItem().equals("Erosion")) {
            imageOperator = Normalization.matrixToBufferedImage(imageMatrix);
            this.imageResult = Morphology.erosion(imageOperator, kernel);
            this.getGraphics().drawImage(imageResult, 550, 50, null);

        } else if(filtrosComboBox.getSelectedItem().equals("Dilation")) {
            imageOperator = Normalization.matrixToBufferedImage(imageMatrix);
            this.imageResult = Morphology.dilation(imageOperator, kernel);
            this.getGraphics().drawImage(imageResult, 550, 50, null);

        } else if(filtrosComboBox.getSelectedItem().equals("Opening")) {    
            imageOperator = Normalization.matrixToBufferedImage(imageMatrix);
            this.imageResult = Morphology.opening(imageOperator, Integer.parseInt(valorText.getText()), kernel);
            this.getGraphics().drawImage(imageResult, 550, 50, null);

        } else if(filtrosComboBox.getSelectedItem().equals("Closure")) {
            imageOperator = Normalization.matrixToBufferedImage(imageMatrix);
            this.imageResult = Morphology.closure(imageOperator, Integer.parseInt(valorText.getText()), kernel);
            this.getGraphics().drawImage(imageResult, 550, 50, null);

        } else if(filtrosComboBox.getSelectedItem().equals("Dilate")) {
            imageOperator = Normalization.matrixToBufferedImage(imageMatrix);
            this.imageResult = Morphology.dilate(imageOperator, Integer.parseInt(valorText.getText()), kernel);
            this.getGraphics().drawImage(imageResult, 550, 50, null);

        } else if(filtrosComboBox.getSelectedItem().equals("Erode")) {
            imageOperator = Normalization.matrixToBufferedImage(imageMatrix);
            this.imageResult = Morphology.erode(imageOperator, Integer.parseInt(valorText.getText()), kernel);
            this.getGraphics().drawImage(imageResult, 550, 50, null);

        }
    }//GEN-LAST:event_aplicarNaImagemButtonActionPerformed

    private void selecionarImgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarImgButtonActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File("src/images/"));
            FileNameExtensionFilter filter = new FileNameExtensionFilter("PGM Images", "pgm");
            fileChooser.setFileFilter(filter);
            int returnVal = fileChooser.showOpenDialog(aplicarNaImagemButton);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
               
                File path = fileChooser.getSelectedFile();
                System.out.println(path);
                createImage(path.getAbsolutePath());
                this.repaint();
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "OPS! N�o foi possivel carregar a imagem.");
        }
    }//GEN-LAST:event_selecionarImgButtonActionPerformed

    /**
     *  Ler o arquivo pgm e monta a popula a matriz imagem
     */
    public int[][] createImage(String path) {
        /*
        */ 
        int width;
        int height;

        InputStream inputStream = null;
        Scanner scan = null;
        try {

            System.out.println(path);
            inputStream = new FileInputStream(path);
            scan = new Scanner(inputStream);

            // Descarta a primeira linha
            scan.nextLine();
            // Read pic width, height and max value
            width = scan.nextInt();
            height = scan.nextInt();
            imgValorMaximo = scan.nextInt();

            BufferedImage bimg = new BufferedImage(width, height, BufferedImage.TYPE_INT_RGB);

            /**
            * Monta a matriz imagem com os pixels da imagem selecionada
            */
            imageMatrix = new int[width][height];

            for (int row = 0; row < height; row++) {
                for (int col = 0; col < width; col++) {
                    // Popula a matriz com os pixels da imagem
                    imageMatrix[row][col] = scan.nextInt();
                }
            }
            inputStream.close();

            /**
            * Monta a matriz imagem com os pixels da imagem selecionada
            */
            for (int row = 0; row < height; row++) {
                for (int col = 0; col < width; col++) {
                    // Prepara a imagem para ser desenhada no jpanel
                    bimg.setRGB(col, row, getCorPixel(imageMatrix[row][col]));
                }
            }

            this.image = bimg;


        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "OPS! criar a imagem.");
        }


        /*
        */
        return imageMatrix;
    }

    /**
     * Exibe a imagem no jPanel
     *
     */
    public void populaImgInPanel(int[][] img, JPanel imgPanel) {
        /**
         * Monta a matriz imagem com os pixels da imagem selecionada
         */
        BufferedImage imagemInput = new BufferedImage(imgWidth, imgHeight, BufferedImage.TYPE_INT_RGB);
        for (int row = 0; row < img.length; row++) {
            for (int col = 0; col < img[0].length; col++) {
                // Prepara a imagem para ser desenhada no jpanel
                imagemInput.setRGB(col, row, getCorPixel(imageMatrix[row][col]));
            }
        }
        /**
         * Exibe a imagem no jpanel
         */
        //panelImageOriginal.setImage(imagemInput);
        panelImageOriginal.getGraphics().drawImage(imagemInput, 75, 75, null);
        //panelImageOriginal.repaint();
    }

    /**
     * Retorna o valor em RGB de acordo com o valor do pixel
     */
    private int getCorPixel(int corRGB) {
        return new Color(corRGB, corRGB, corRGB).getRGB();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicarNaImagemButton;
    private javax.swing.JComboBox<String> filtrosComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelImageOriginal;
    private javax.swing.JPanel panelImageResult;
    private javax.swing.JButton selecionarImgButton;
    private javax.swing.JLabel valorLabel;
    private javax.swing.JTextField valorText;
    // End of variables declaration//GEN-END:variables
}
